// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new applications API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for applications API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetProfilesForApplication(params *GetProfilesForApplicationParams, authInfo runtime.ClientAuthInfoWriter) (*GetProfilesForApplicationOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetProfilesForApplication retrieves profiles

  Retrieve all the Profiles based on selected type for the specified application.
If the user is working within a team context, the application must belong to the user's currently selected team.

*/
func (a *Client) GetProfilesForApplication(params *GetProfilesForApplicationParams, authInfo runtime.ClientAuthInfoWriter) (*GetProfilesForApplicationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetProfilesForApplicationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getProfilesForApplication",
		Method:             "GET",
		PathPattern:        "/applications/{applicationId}/profiles",
		ProducesMediaTypes: []string{"application/json", "application/xml"},
		ConsumesMediaTypes: []string{"application/json", "application/xml"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetProfilesForApplicationReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetProfilesForApplicationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getProfilesForApplication: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
