// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProfileByIDParams creates a new GetProfileByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProfileByIDParams() *GetProfileByIDParams {
	return &GetProfileByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProfileByIDParamsWithTimeout creates a new GetProfileByIDParams object
// with the ability to set a timeout on a request.
func NewGetProfileByIDParamsWithTimeout(timeout time.Duration) *GetProfileByIDParams {
	return &GetProfileByIDParams{
		timeout: timeout,
	}
}

// NewGetProfileByIDParamsWithContext creates a new GetProfileByIDParams object
// with the ability to set a context for a request.
func NewGetProfileByIDParamsWithContext(ctx context.Context) *GetProfileByIDParams {
	return &GetProfileByIDParams{
		Context: ctx,
	}
}

// NewGetProfileByIDParamsWithHTTPClient creates a new GetProfileByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProfileByIDParamsWithHTTPClient(client *http.Client) *GetProfileByIDParams {
	return &GetProfileByIDParams{
		HTTPClient: client,
	}
}

/* GetProfileByIDParams contains all the parameters to send to the API endpoint
   for the get profile by Id operation.

   Typically these are written to a http.Request.
*/
type GetProfileByIDParams struct {

	/* XAxwayTeamID.

	   The currently selected team if the user is using the system within a team context
	*/
	XAxwayTeamID *string

	/* XAxwayTenantID.

	   The tenant id
	*/
	XAxwayTenantID *string

	/* ApplicationID.

	   The application id
	*/
	ApplicationID string

	/* ProfileID.

	   The Profile id
	*/
	ProfileID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get profile by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProfileByIDParams) WithDefaults() *GetProfileByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get profile by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProfileByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get profile by Id params
func (o *GetProfileByIDParams) WithTimeout(timeout time.Duration) *GetProfileByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get profile by Id params
func (o *GetProfileByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get profile by Id params
func (o *GetProfileByIDParams) WithContext(ctx context.Context) *GetProfileByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get profile by Id params
func (o *GetProfileByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get profile by Id params
func (o *GetProfileByIDParams) WithHTTPClient(client *http.Client) *GetProfileByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get profile by Id params
func (o *GetProfileByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAxwayTeamID adds the xAxwayTeamID to the get profile by Id params
func (o *GetProfileByIDParams) WithXAxwayTeamID(xAxwayTeamID *string) *GetProfileByIDParams {
	o.SetXAxwayTeamID(xAxwayTeamID)
	return o
}

// SetXAxwayTeamID adds the xAxwayTeamId to the get profile by Id params
func (o *GetProfileByIDParams) SetXAxwayTeamID(xAxwayTeamID *string) {
	o.XAxwayTeamID = xAxwayTeamID
}

// WithXAxwayTenantID adds the xAxwayTenantID to the get profile by Id params
func (o *GetProfileByIDParams) WithXAxwayTenantID(xAxwayTenantID *string) *GetProfileByIDParams {
	o.SetXAxwayTenantID(xAxwayTenantID)
	return o
}

// SetXAxwayTenantID adds the xAxwayTenantId to the get profile by Id params
func (o *GetProfileByIDParams) SetXAxwayTenantID(xAxwayTenantID *string) {
	o.XAxwayTenantID = xAxwayTenantID
}

// WithApplicationID adds the applicationID to the get profile by Id params
func (o *GetProfileByIDParams) WithApplicationID(applicationID string) *GetProfileByIDParams {
	o.SetApplicationID(applicationID)
	return o
}

// SetApplicationID adds the applicationId to the get profile by Id params
func (o *GetProfileByIDParams) SetApplicationID(applicationID string) {
	o.ApplicationID = applicationID
}

// WithProfileID adds the profileID to the get profile by Id params
func (o *GetProfileByIDParams) WithProfileID(profileID string) *GetProfileByIDParams {
	o.SetProfileID(profileID)
	return o
}

// SetProfileID adds the profileId to the get profile by Id params
func (o *GetProfileByIDParams) SetProfileID(profileID string) {
	o.ProfileID = profileID
}

// WriteToRequest writes these params to a swagger request
func (o *GetProfileByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XAxwayTeamID != nil {

		// header param X-Axway-Team-Id
		if err := r.SetHeaderParam("X-Axway-Team-Id", *o.XAxwayTeamID); err != nil {
			return err
		}
	}

	if o.XAxwayTenantID != nil {

		// header param X-Axway-Tenant-Id
		if err := r.SetHeaderParam("X-Axway-Tenant-Id", *o.XAxwayTenantID); err != nil {
			return err
		}
	}

	// path param applicationId
	if err := r.SetPathParam("applicationId", o.ApplicationID); err != nil {
		return err
	}

	// path param profileId
	if err := r.SetPathParam("profileId", o.ProfileID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
