// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetProfilesForApplicationReader is a Reader for the GetProfilesForApplication structure.
type GetProfilesForApplicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProfilesForApplicationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProfilesForApplicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProfilesForApplicationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProfilesForApplicationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetProfilesForApplicationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProfilesForApplicationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProfilesForApplicationOK creates a GetProfilesForApplicationOK with default headers values
func NewGetProfilesForApplicationOK() *GetProfilesForApplicationOK {
	return &GetProfilesForApplicationOK{}
}

/* GetProfilesForApplicationOK describes a response with status code 200, with default header values.

The list of Profiles specified by type for application
*/
type GetProfilesForApplicationOK struct {
	Payload []interface{}
}

func (o *GetProfilesForApplicationOK) Error() string {
	return fmt.Sprintf("[GET /applications/{applicationId}/profiles][%d] getProfilesForApplicationOK  %+v", 200, o.Payload)
}
func (o *GetProfilesForApplicationOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *GetProfilesForApplicationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProfilesForApplicationBadRequest creates a GetProfilesForApplicationBadRequest with default headers values
func NewGetProfilesForApplicationBadRequest() *GetProfilesForApplicationBadRequest {
	return &GetProfilesForApplicationBadRequest{}
}

/* GetProfilesForApplicationBadRequest describes a response with status code 400, with default header values.

Bad Request, failed to validate request parameters
*/
type GetProfilesForApplicationBadRequest struct {
}

func (o *GetProfilesForApplicationBadRequest) Error() string {
	return fmt.Sprintf("[GET /applications/{applicationId}/profiles][%d] getProfilesForApplicationBadRequest ", 400)
}

func (o *GetProfilesForApplicationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProfilesForApplicationUnauthorized creates a GetProfilesForApplicationUnauthorized with default headers values
func NewGetProfilesForApplicationUnauthorized() *GetProfilesForApplicationUnauthorized {
	return &GetProfilesForApplicationUnauthorized{}
}

/* GetProfilesForApplicationUnauthorized describes a response with status code 401, with default header values.

Unauthorized, user failed to authenticate
*/
type GetProfilesForApplicationUnauthorized struct {
}

func (o *GetProfilesForApplicationUnauthorized) Error() string {
	return fmt.Sprintf("[GET /applications/{applicationId}/profiles][%d] getProfilesForApplicationUnauthorized ", 401)
}

func (o *GetProfilesForApplicationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProfilesForApplicationForbidden creates a GetProfilesForApplicationForbidden with default headers values
func NewGetProfilesForApplicationForbidden() *GetProfilesForApplicationForbidden {
	return &GetProfilesForApplicationForbidden{}
}

/* GetProfilesForApplicationForbidden describes a response with status code 403, with default header values.

Forbidden, the user does not have the correct permissions to call this API
*/
type GetProfilesForApplicationForbidden struct {
}

func (o *GetProfilesForApplicationForbidden) Error() string {
	return fmt.Sprintf("[GET /applications/{applicationId}/profiles][%d] getProfilesForApplicationForbidden ", 403)
}

func (o *GetProfilesForApplicationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetProfilesForApplicationNotFound creates a GetProfilesForApplicationNotFound with default headers values
func NewGetProfilesForApplicationNotFound() *GetProfilesForApplicationNotFound {
	return &GetProfilesForApplicationNotFound{}
}

/* GetProfilesForApplicationNotFound describes a response with status code 404, with default header values.

Not Found, a required entity was not found
*/
type GetProfilesForApplicationNotFound struct {
}

func (o *GetProfilesForApplicationNotFound) Error() string {
	return fmt.Sprintf("[GET /applications/{applicationId}/profiles][%d] getProfilesForApplicationNotFound ", 404)
}

func (o *GetProfilesForApplicationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
