image: docker:dind

variables:
  PROJECT: "agents-kong"

  # Fortify
  FORTIFY_PROJECT: "10853"
  FORTIFY_BUILD_ID: "agents-kong"
  FORTIFY_INCLUDE: "**/*.go"
  FORTIFY_EXCLUDE: "**/*_test.go"

  # Blackduck
  BLACKDUCK_PROJECT_NAME: "Amplify - APIC Kong Agents"

  # SRM
  SRM_PROJECT_NAME: "$BLACKDUCK_PROJECT_NAME"
  SRM_PROJECT_ID: "256"

########################################
# set up custom names for the pipelines of releases and nightly schedules
########################################
  PIPELINE_NAME: "$CI_COMMIT_MESSAGE"

workflow:
  name: "$PIPELINE_NAME"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $COMPONENT_TESTS_ONLY == "y"
      variables:
        PIPELINE_NAME: "Scheduled nightly tests"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $VERSION == "SNAPSHOT"
      variables:
        PIPELINE_NAME: "Scheduled nightly SecurityCI default branch"
    - if: $CI_PIPELINE_SOURCE == "schedule" && $VERSION == "LATEST"
      variables:
        PIPELINE_NAME: "Scheduled nightly SecurityCI on LATEST"
    - when: always

include:
  - project: "apigov/gitlabci"
    ref: master
    file: "/.gitlab-ci-sonar.yml"
  - project: "apigov/beano_cicd"
    ref: APIGOV-29656
    # the order of these include files is important
    file:
      - "/gitlabci/variables.yml"
      - "/gitlabci/restrictions.yml"
      - "/gitlabci/jobs.yml"
  - project: "scurity/gitlabci"
    ref: APIGOV-29656
    file:
      - "/.gitlab-ci-fortify.yml"
      - "/.gitlab-ci-twistlock.yml"
      - "/.gitlab-ci-iriusrisk.yml"
      - "/.gitlab-ci-blackduck.yml"
      - "/.gitlab-ci-security.yml"
  - project: "apigov/beano_cicd"
    ref: APIGOV-29656
    # the order of these include files is important
    file:
      - "/gitlabci/securityjobs.yml"
      - "/gitlabci/securityjobsformirror.yml"

stages:
  - test
  - qa-test
  - sonar-preview
  - sonar-publish
  - security-scans
  - security-review

twistlock-discovery:
  extends: .twistlock
  rules:
    - !reference [.security-snapshot-rules, rules]
  before_script:
    - apk --no-cache update && apk add make
    - make docker-da
    - export IMAGE_NAME=kong-discovery-agent:latest
    - echo "TL_DA=true" >> build.env

twistlock-traceability:
  extends: .twistlock
  rules:
    - !reference [.security-snapshot-rules, rules]
  before_script:
    - apk --no-cache update && apk add make
    - make docker-ta
    - export IMAGE_NAME=kong-traceability-agent:latest
    - echo "TL_TA=true" >> build.env

twistlock-discovery:on-schedule:
  variables:
    AGENT_NAME: "kong_discovery_agent"

twistlock-traceability:on-schedule:
  variables:
    AGENT_NAME: "kong_traceability_agent"
