run:
  timeout: 8m
  modules-download-mode: readonly
linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - structcheck
    - varcheck
    - deadcode
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - revive
    - stylecheck
    - typecheck
    - unconvert
    - unparam
