discovery:
  replicaCount: 1
  image:
    repository: ghcr.io/axway/kong_discovery_agent
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 

traceability:
  replicaCount: 1
  image:
    repository: ghcr.io/axway/kong_traceability_agent
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
# Health Check port
statusPort: 8989

kong:
  acl:
    disable: false
  enable:
    traceability: false
  admin:
    url:
    auth:
      apikey:
        header:
        value:
      basicAuth:
        username:
        password:
  proxy:
    host:
    basePath:
    ports:
      http:
        disable:
        value: 
      https:
        disable: 
        value: 
  spec:
    filter:
    urlPaths: []
    localPath:
  logs:
    http:
      path:
      port:

# Add any environment variable overrides here
env: {}

secrets:
  credentials: "kong-agent-creds"
  keys: "kong-agent-keys"
podAnnotations:
podSecurityContext:
  supplementalGroups: [2500]
  fsGroupChangePolicy: "OnRootMismatch"
securityContext:
tolerations:
affinity:
nodeSelector: {}
# Add additional labels to the agent deployment which may be required based on your configuration
additionalLabels:
serviceAccount:
  annotations:

  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources: {}

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
