// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIDeploymentState API deployment state
//
// swagger:model APIDeploymentState
type APIDeploymentState struct {

	// value
	// Required: true
	// Enum: [DEPLOYED_ACTIVE DEPLOYED_INACTIVE UNDEPLOYED]
	Value *string `json:"value"`
}

// Validate validates this API deployment state
func (m *APIDeploymentState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var apiDeploymentStateTypeValuePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DEPLOYED_ACTIVE","DEPLOYED_INACTIVE","UNDEPLOYED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiDeploymentStateTypeValuePropEnum = append(apiDeploymentStateTypeValuePropEnum, v)
	}
}

const (

	// APIDeploymentStateValueDEPLOYEDACTIVE captures enum value "DEPLOYED_ACTIVE"
	APIDeploymentStateValueDEPLOYEDACTIVE string = "DEPLOYED_ACTIVE"

	// APIDeploymentStateValueDEPLOYEDINACTIVE captures enum value "DEPLOYED_INACTIVE"
	APIDeploymentStateValueDEPLOYEDINACTIVE string = "DEPLOYED_INACTIVE"

	// APIDeploymentStateValueUNDEPLOYED captures enum value "UNDEPLOYED"
	APIDeploymentStateValueUNDEPLOYED string = "UNDEPLOYED"
)

// prop value enum
func (m *APIDeploymentState) validateValueEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, apiDeploymentStateTypeValuePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *APIDeploymentState) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	// value enum
	if err := m.validateValueEnum("value", "body", *m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this API deployment state based on context it is used
func (m *APIDeploymentState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIDeploymentState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIDeploymentState) UnmarshalBinary(b []byte) error {
	var res APIDeploymentState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
