// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIAccess API access
//
// swagger:model APIAccess
type APIAccess struct {

	// The id of the application to which this API access belongs
	// Required: true
	// Max Length: 32
	// Min Length: 32
	ApplicationID *string `json:"applicationId"`

	// The id for the API access
	// Max Length: 32
	// Min Length: 32
	ID string `json:"id,omitempty"`

	// metadata
	Metadata *AuditMetadata `json:"metadata,omitempty"`

	// policy overrides
	PolicyOverrides *PolicyOverrides `json:"policyOverrides,omitempty"`

	// The API proxy id
	// Required: true
	// Max Length: 32
	// Min Length: 32
	ProxyID *string `json:"proxyId"`

	// The id of the runtime group to which this API access belongs
	// Required: true
	// Max Length: 32
	// Min Length: 32
	RuntimeGroupID *string `json:"runtimeGroupId"`
}

// Validate validates this API access
func (m *APIAccess) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApplicationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePolicyOverrides(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRuntimeGroupID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIAccess) validateApplicationID(formats strfmt.Registry) error {

	if err := validate.Required("applicationId", "body", m.ApplicationID); err != nil {
		return err
	}

	if err := validate.MinLength("applicationId", "body", *m.ApplicationID, 32); err != nil {
		return err
	}

	if err := validate.MaxLength("applicationId", "body", *m.ApplicationID, 32); err != nil {
		return err
	}

	return nil
}

func (m *APIAccess) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.MinLength("id", "body", m.ID, 32); err != nil {
		return err
	}

	if err := validate.MaxLength("id", "body", m.ID, 32); err != nil {
		return err
	}

	return nil
}

func (m *APIAccess) validateMetadata(formats strfmt.Registry) error {
	if swag.IsZero(m.Metadata) { // not required
		return nil
	}

	if m.Metadata != nil {
		if err := m.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *APIAccess) validatePolicyOverrides(formats strfmt.Registry) error {
	if swag.IsZero(m.PolicyOverrides) { // not required
		return nil
	}

	if m.PolicyOverrides != nil {
		if err := m.PolicyOverrides.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("policyOverrides")
			}
			return err
		}
	}

	return nil
}

func (m *APIAccess) validateProxyID(formats strfmt.Registry) error {

	if err := validate.Required("proxyId", "body", m.ProxyID); err != nil {
		return err
	}

	if err := validate.MinLength("proxyId", "body", *m.ProxyID, 32); err != nil {
		return err
	}

	if err := validate.MaxLength("proxyId", "body", *m.ProxyID, 32); err != nil {
		return err
	}

	return nil
}

func (m *APIAccess) validateRuntimeGroupID(formats strfmt.Registry) error {

	if err := validate.Required("runtimeGroupId", "body", m.RuntimeGroupID); err != nil {
		return err
	}

	if err := validate.MinLength("runtimeGroupId", "body", *m.RuntimeGroupID, 32); err != nil {
		return err
	}

	if err := validate.MaxLength("runtimeGroupId", "body", *m.RuntimeGroupID, 32); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this API access based on the context it is used
func (m *APIAccess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePolicyOverrides(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIAccess) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata != nil {
		if err := m.Metadata.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *APIAccess) contextValidatePolicyOverrides(ctx context.Context, formats strfmt.Registry) error {

	if m.PolicyOverrides != nil {
		if err := m.PolicyOverrides.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("policyOverrides")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIAccess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIAccess) UnmarshalBinary(b []byte) error {
	var res APIAccess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
