// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthorizationResponse authorization response
//
// swagger:model AuthorizationResponse
type AuthorizationResponse struct {
	Application

	// policy overrides
	PolicyOverrides *PolicyOverrides `json:"policyOverrides,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *AuthorizationResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Application
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Application = aO0

	// AO1
	var dataAO1 struct {
		PolicyOverrides *PolicyOverrides `json:"policyOverrides,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.PolicyOverrides = dataAO1.PolicyOverrides

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m AuthorizationResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Application)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		PolicyOverrides *PolicyOverrides `json:"policyOverrides,omitempty"`
	}

	dataAO1.PolicyOverrides = m.PolicyOverrides

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this authorization response
func (m *AuthorizationResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Application
	if err := m.Application.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePolicyOverrides(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthorizationResponse) validatePolicyOverrides(formats strfmt.Registry) error {

	if swag.IsZero(m.PolicyOverrides) { // not required
		return nil
	}

	if m.PolicyOverrides != nil {
		if err := m.PolicyOverrides.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("policyOverrides")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this authorization response based on the context it is used
func (m *AuthorizationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Application
	if err := m.Application.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePolicyOverrides(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthorizationResponse) contextValidatePolicyOverrides(ctx context.Context, formats strfmt.Registry) error {

	if m.PolicyOverrides != nil {
		if err := m.PolicyOverrides.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("policyOverrides")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthorizationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthorizationResponse) UnmarshalBinary(b []byte) error {
	var res AuthorizationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
