// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EvaluatedPermission evaluated permission
//
// swagger:model EvaluatedPermission
type EvaluatedPermission struct {

	// The permission string e.g. team:create
	// Max Length: 100
	// Min Length: 1
	// Pattern: ^[a-z0-9\*\:\.-]*$
	Evaluated string `json:"evaluated,omitempty"`

	// The id for the permission
	// Max Length: 32
	// Min Length: 32
	ID string `json:"id,omitempty"`
}

// Validate validates this evaluated permission
func (m *EvaluatedPermission) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEvaluated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EvaluatedPermission) validateEvaluated(formats strfmt.Registry) error {
	if swag.IsZero(m.Evaluated) { // not required
		return nil
	}

	if err := validate.MinLength("evaluated", "body", m.Evaluated, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("evaluated", "body", m.Evaluated, 100); err != nil {
		return err
	}

	if err := validate.Pattern("evaluated", "body", m.Evaluated, `^[a-z0-9\*\:\.-]*$`); err != nil {
		return err
	}

	return nil
}

func (m *EvaluatedPermission) validateID(formats strfmt.Registry) error {
	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.MinLength("id", "body", m.ID, 32); err != nil {
		return err
	}

	if err := validate.MaxLength("id", "body", m.ID, 32); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this evaluated permission based on context it is used
func (m *EvaluatedPermission) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EvaluatedPermission) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EvaluatedPermission) UnmarshalBinary(b []byte) error {
	var res EvaluatedPermission
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
