// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FeatureFlagStatus feature flag status
//
// swagger:model FeatureFlagStatus
type FeatureFlagStatus struct {

	// Defines if the feature flag for the provided key is allowed
	Allowed bool `json:"allowed,omitempty"`
}

// Validate validates this feature flag status
func (m *FeatureFlagStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this feature flag status based on context it is used
func (m *FeatureFlagStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FeatureFlagStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FeatureFlagStatus) UnmarshalBinary(b []byte) error {
	var res FeatureFlagStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
