// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Governance governance
//
// swagger:model Governance
type Governance struct {

	// method overrides
	MethodOverrides []*MethodOverride `json:"methodOverrides"`

	// The pipeline of policies associated with the request (Inbound).
	RequestPolicies []string `json:"requestPolicies"`

	// The pipeline of policies associated with the response (Outbound).
	ResponsePolicies []string `json:"responsePolicies"`
}

// Validate validates this governance
func (m *Governance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMethodOverrides(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Governance) validateMethodOverrides(formats strfmt.Registry) error {
	if swag.IsZero(m.MethodOverrides) { // not required
		return nil
	}

	for i := 0; i < len(m.MethodOverrides); i++ {
		if swag.IsZero(m.MethodOverrides[i]) { // not required
			continue
		}

		if m.MethodOverrides[i] != nil {
			if err := m.MethodOverrides[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("methodOverrides" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this governance based on the context it is used
func (m *Governance) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMethodOverrides(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Governance) contextValidateMethodOverrides(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.MethodOverrides); i++ {

		if m.MethodOverrides[i] != nil {
			if err := m.MethodOverrides[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("methodOverrides" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Governance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Governance) UnmarshalBinary(b []byte) error {
	var res Governance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
