// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// JWTKeyProfile j w t key profile
//
// swagger:model JWTKeyProfile
type JWTKeyProfile struct {
	applicationIdField string

	descriptionField string

	enabledField *bool

	idField string

	metadataField *AuditMetadata

	nameField *string

	// The end time of the validity period, if not specified the JWT key will not expire. Date should be in ISO-8601 format (ig. "2019-03-11T23:59:59.000Z").
	// Pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})?(Z)?$
	EndTimestamp string `json:"endTimestamp,omitempty"`

	// The JWK formatted RSA public key
	// Max Length: 2048
	Jwk string `json:"jwk,omitempty"`

	// The key id - that is genereated by the server based on the pem encoded public key
	// Max Length: 50
	// Min Length: 1
	KeyID string `json:"keyId,omitempty"`

	// The PEM-formatted RSA public key
	// Required: true
	// Max Length: 524288
	// Pattern: ^(-----BEGIN PUBLIC KEY-----([A-Za-z0-9+\/=\s]+)-----END PUBLIC KEY-----)*$
	PemEncodedPublicKey *string `json:"pemEncodedPublicKey"`

	// The start time of the validity period, if not specified the JWT key will be valid from creation time. Date should be in ISO-8601 format (ig. "2019-03-11T23:59:59.000Z").
	// Pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})?(Z)?$
	StartTimestamp string `json:"startTimestamp,omitempty"`
}

// ApplicationID gets the application Id of this subtype
func (m *JWTKeyProfile) ApplicationID() string {
	return m.applicationIdField
}

// SetApplicationID sets the application Id of this subtype
func (m *JWTKeyProfile) SetApplicationID(val string) {
	m.applicationIdField = val
}

// Description gets the description of this subtype
func (m *JWTKeyProfile) Description() string {
	return m.descriptionField
}

// SetDescription sets the description of this subtype
func (m *JWTKeyProfile) SetDescription(val string) {
	m.descriptionField = val
}

// Enabled gets the enabled of this subtype
func (m *JWTKeyProfile) Enabled() *bool {
	return m.enabledField
}

// SetEnabled sets the enabled of this subtype
func (m *JWTKeyProfile) SetEnabled(val *bool) {
	m.enabledField = val
}

// ID gets the id of this subtype
func (m *JWTKeyProfile) ID() string {
	return m.idField
}

// SetID sets the id of this subtype
func (m *JWTKeyProfile) SetID(val string) {
	m.idField = val
}

// Metadata gets the metadata of this subtype
func (m *JWTKeyProfile) Metadata() *AuditMetadata {
	return m.metadataField
}

// SetMetadata sets the metadata of this subtype
func (m *JWTKeyProfile) SetMetadata(val *AuditMetadata) {
	m.metadataField = val
}

// Name gets the name of this subtype
func (m *JWTKeyProfile) Name() *string {
	return m.nameField
}

// SetName sets the name of this subtype
func (m *JWTKeyProfile) SetName(val *string) {
	m.nameField = val
}

// Type gets the type of this subtype
func (m *JWTKeyProfile) Type() string {
	return "JWTKeyProfile"
}

// SetType sets the type of this subtype
func (m *JWTKeyProfile) SetType(val string) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *JWTKeyProfile) UnmarshalJSON(raw []byte) error {
	var data struct {

		// The end time of the validity period, if not specified the JWT key will not expire. Date should be in ISO-8601 format (ig. "2019-03-11T23:59:59.000Z").
		// Pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})?(Z)?$
		EndTimestamp string `json:"endTimestamp,omitempty"`

		// The JWK formatted RSA public key
		// Max Length: 2048
		Jwk string `json:"jwk,omitempty"`

		// The key id - that is genereated by the server based on the pem encoded public key
		// Max Length: 50
		// Min Length: 1
		KeyID string `json:"keyId,omitempty"`

		// The PEM-formatted RSA public key
		// Required: true
		// Max Length: 524288
		// Pattern: ^(-----BEGIN PUBLIC KEY-----([A-Za-z0-9+\/=\s]+)-----END PUBLIC KEY-----)*$
		PemEncodedPublicKey *string `json:"pemEncodedPublicKey"`

		// The start time of the validity period, if not specified the JWT key will be valid from creation time. Date should be in ISO-8601 format (ig. "2019-03-11T23:59:59.000Z").
		// Pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})?(Z)?$
		StartTimestamp string `json:"startTimestamp,omitempty"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		ApplicationID string `json:"applicationId,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		ID string `json:"id,omitempty"`

		Metadata *AuditMetadata `json:"metadata,omitempty"`

		Name *string `json:"name"`

		Type string `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result JWTKeyProfile

	result.applicationIdField = base.ApplicationID

	result.descriptionField = base.Description

	result.enabledField = base.Enabled

	result.idField = base.ID

	result.metadataField = base.Metadata

	result.nameField = base.Name

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.EndTimestamp = data.EndTimestamp
	result.Jwk = data.Jwk
	result.KeyID = data.KeyID
	result.PemEncodedPublicKey = data.PemEncodedPublicKey
	result.StartTimestamp = data.StartTimestamp

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m JWTKeyProfile) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// The end time of the validity period, if not specified the JWT key will not expire. Date should be in ISO-8601 format (ig. "2019-03-11T23:59:59.000Z").
		// Pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})?(Z)?$
		EndTimestamp string `json:"endTimestamp,omitempty"`

		// The JWK formatted RSA public key
		// Max Length: 2048
		Jwk string `json:"jwk,omitempty"`

		// The key id - that is genereated by the server based on the pem encoded public key
		// Max Length: 50
		// Min Length: 1
		KeyID string `json:"keyId,omitempty"`

		// The PEM-formatted RSA public key
		// Required: true
		// Max Length: 524288
		// Pattern: ^(-----BEGIN PUBLIC KEY-----([A-Za-z0-9+\/=\s]+)-----END PUBLIC KEY-----)*$
		PemEncodedPublicKey *string `json:"pemEncodedPublicKey"`

		// The start time of the validity period, if not specified the JWT key will be valid from creation time. Date should be in ISO-8601 format (ig. "2019-03-11T23:59:59.000Z").
		// Pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})?(Z)?$
		StartTimestamp string `json:"startTimestamp,omitempty"`
	}{

		EndTimestamp: m.EndTimestamp,

		Jwk: m.Jwk,

		KeyID: m.KeyID,

		PemEncodedPublicKey: m.PemEncodedPublicKey,

		StartTimestamp: m.StartTimestamp,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		ApplicationID string `json:"applicationId,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		ID string `json:"id,omitempty"`

		Metadata *AuditMetadata `json:"metadata,omitempty"`

		Name *string `json:"name"`

		Type string `json:"type"`
	}{

		ApplicationID: m.ApplicationID(),

		Description: m.Description(),

		Enabled: m.Enabled(),

		ID: m.ID(),

		Metadata: m.Metadata(),

		Name: m.Name(),

		Type: m.Type(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this j w t key profile
func (m *JWTKeyProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApplicationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEndTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJwk(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePemEncodedPublicKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JWTKeyProfile) validateApplicationID(formats strfmt.Registry) error {

	if swag.IsZero(m.ApplicationID()) { // not required
		return nil
	}

	if err := validate.MinLength("applicationId", "body", m.ApplicationID(), 32); err != nil {
		return err
	}

	if err := validate.MaxLength("applicationId", "body", m.ApplicationID(), 32); err != nil {
		return err
	}

	return nil
}

func (m *JWTKeyProfile) validateDescription(formats strfmt.Registry) error {

	if swag.IsZero(m.Description()) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description(), 350); err != nil {
		return err
	}

	if err := validate.Pattern("description", "body", m.Description(), `^[ -~\s]*$`); err != nil {
		return err
	}

	return nil
}

func (m *JWTKeyProfile) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID()) { // not required
		return nil
	}

	if err := validate.MinLength("id", "body", m.ID(), 32); err != nil {
		return err
	}

	if err := validate.MaxLength("id", "body", m.ID(), 32); err != nil {
		return err
	}

	return nil
}

func (m *JWTKeyProfile) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(m.Metadata()) { // not required
		return nil
	}

	if m.Metadata() != nil {
		if err := m.Metadata().Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *JWTKeyProfile) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name()); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name(), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name(), 100); err != nil {
		return err
	}

	return nil
}

func (m *JWTKeyProfile) validateEndTimestamp(formats strfmt.Registry) error {

	if swag.IsZero(m.EndTimestamp) { // not required
		return nil
	}

	if err := validate.Pattern("endTimestamp", "body", m.EndTimestamp, `^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})?(Z)?$`); err != nil {
		return err
	}

	return nil
}

func (m *JWTKeyProfile) validateJwk(formats strfmt.Registry) error {

	if swag.IsZero(m.Jwk) { // not required
		return nil
	}

	if err := validate.MaxLength("jwk", "body", m.Jwk, 2048); err != nil {
		return err
	}

	return nil
}

func (m *JWTKeyProfile) validateKeyID(formats strfmt.Registry) error {

	if swag.IsZero(m.KeyID) { // not required
		return nil
	}

	if err := validate.MinLength("keyId", "body", m.KeyID, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("keyId", "body", m.KeyID, 50); err != nil {
		return err
	}

	return nil
}

func (m *JWTKeyProfile) validatePemEncodedPublicKey(formats strfmt.Registry) error {

	if err := validate.Required("pemEncodedPublicKey", "body", m.PemEncodedPublicKey); err != nil {
		return err
	}

	if err := validate.MaxLength("pemEncodedPublicKey", "body", *m.PemEncodedPublicKey, 524288); err != nil {
		return err
	}

	if err := validate.Pattern("pemEncodedPublicKey", "body", *m.PemEncodedPublicKey, `^(-----BEGIN PUBLIC KEY-----([A-Za-z0-9+\/=\s]+)-----END PUBLIC KEY-----)*$`); err != nil {
		return err
	}

	return nil
}

func (m *JWTKeyProfile) validateStartTimestamp(formats strfmt.Registry) error {

	if swag.IsZero(m.StartTimestamp) { // not required
		return nil
	}

	if err := validate.Pattern("startTimestamp", "body", m.StartTimestamp, `^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]{3})?(Z)?$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this j w t key profile based on the context it is used
func (m *JWTKeyProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JWTKeyProfile) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata() != nil {
		if err := m.Metadata().ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *JWTKeyProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JWTKeyProfile) UnmarshalBinary(b []byte) error {
	var res JWTKeyProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
