// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LogicalInstanceState logical instance state
//
// swagger:model LogicalInstanceState
type LogicalInstanceState struct {

	// value
	// Required: true
	// Enum: [ACTIVE SUSPENDED]
	Value *string `json:"value"`
}

// Validate validates this logical instance state
func (m *LogicalInstanceState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var logicalInstanceStateTypeValuePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ACTIVE","SUSPENDED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		logicalInstanceStateTypeValuePropEnum = append(logicalInstanceStateTypeValuePropEnum, v)
	}
}

const (

	// LogicalInstanceStateValueACTIVE captures enum value "ACTIVE"
	LogicalInstanceStateValueACTIVE string = "ACTIVE"

	// LogicalInstanceStateValueSUSPENDED captures enum value "SUSPENDED"
	LogicalInstanceStateValueSUSPENDED string = "SUSPENDED"
)

// prop value enum
func (m *LogicalInstanceState) validateValueEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, logicalInstanceStateTypeValuePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *LogicalInstanceState) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	// value enum
	if err := m.validateValueEnum("value", "body", *m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this logical instance state based on context it is used
func (m *LogicalInstanceState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LogicalInstanceState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LogicalInstanceState) UnmarshalBinary(b []byte) error {
	var res LogicalInstanceState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
