// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PolicyOverrides policy overrides
//
// swagger:model PolicyOverrides
type PolicyOverrides struct {

	// rate limit
	RateLimit *RateLimitingPolicyOverride `json:"rateLimit,omitempty"`
}

// Validate validates this policy overrides
func (m *PolicyOverrides) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRateLimit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PolicyOverrides) validateRateLimit(formats strfmt.Registry) error {
	if swag.IsZero(m.RateLimit) { // not required
		return nil
	}

	if m.RateLimit != nil {
		if err := m.RateLimit.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rateLimit")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this policy overrides based on the context it is used
func (m *PolicyOverrides) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRateLimit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PolicyOverrides) contextValidateRateLimit(ctx context.Context, formats strfmt.Registry) error {

	if m.RateLimit != nil {
		if err := m.RateLimit.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rateLimit")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PolicyOverrides) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyOverrides) UnmarshalBinary(b []byte) error {
	var res PolicyOverrides
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
