// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PublicCertificateProfile public certificate profile
//
// swagger:model PublicCertificateProfile
type PublicCertificateProfile struct {
	applicationIdField string

	descriptionField string

	enabledField *bool

	idField string

	metadataField *AuditMetadata

	nameField *string

	// The login name
	// Required: true
	// Max Length: 256
	// Min Length: 1
	// Pattern: ^[^\!|\#|\*|\||\,|\;|\:]*$
	Login *string `json:"login"`

	// The public certificate in PKCS7, CRT, DER - PEM or Base64 encoded format
	// Required: true
	// Max Length: 524288
	// Pattern: ^(-----BEGIN CERTIFICATE-----([A-Za-z0-9+\/=\s]+)-----END CERTIFICATE-----)|^(-----BEGIN PKCS7-----([A-Za-z0-9+\/=\s]+)-----END PKCS7-----)$
	PublicCertificate *string `json:"publicCertificate"`
}

// ApplicationID gets the application Id of this subtype
func (m *PublicCertificateProfile) ApplicationID() string {
	return m.applicationIdField
}

// SetApplicationID sets the application Id of this subtype
func (m *PublicCertificateProfile) SetApplicationID(val string) {
	m.applicationIdField = val
}

// Description gets the description of this subtype
func (m *PublicCertificateProfile) Description() string {
	return m.descriptionField
}

// SetDescription sets the description of this subtype
func (m *PublicCertificateProfile) SetDescription(val string) {
	m.descriptionField = val
}

// Enabled gets the enabled of this subtype
func (m *PublicCertificateProfile) Enabled() *bool {
	return m.enabledField
}

// SetEnabled sets the enabled of this subtype
func (m *PublicCertificateProfile) SetEnabled(val *bool) {
	m.enabledField = val
}

// ID gets the id of this subtype
func (m *PublicCertificateProfile) ID() string {
	return m.idField
}

// SetID sets the id of this subtype
func (m *PublicCertificateProfile) SetID(val string) {
	m.idField = val
}

// Metadata gets the metadata of this subtype
func (m *PublicCertificateProfile) Metadata() *AuditMetadata {
	return m.metadataField
}

// SetMetadata sets the metadata of this subtype
func (m *PublicCertificateProfile) SetMetadata(val *AuditMetadata) {
	m.metadataField = val
}

// Name gets the name of this subtype
func (m *PublicCertificateProfile) Name() *string {
	return m.nameField
}

// SetName sets the name of this subtype
func (m *PublicCertificateProfile) SetName(val *string) {
	m.nameField = val
}

// Type gets the type of this subtype
func (m *PublicCertificateProfile) Type() string {
	return "PublicCertificateProfile"
}

// SetType sets the type of this subtype
func (m *PublicCertificateProfile) SetType(val string) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *PublicCertificateProfile) UnmarshalJSON(raw []byte) error {
	var data struct {

		// The login name
		// Required: true
		// Max Length: 256
		// Min Length: 1
		// Pattern: ^[^\!|\#|\*|\||\,|\;|\:]*$
		Login *string `json:"login"`

		// The public certificate in PKCS7, CRT, DER - PEM or Base64 encoded format
		// Required: true
		// Max Length: 524288
		// Pattern: ^(-----BEGIN CERTIFICATE-----([A-Za-z0-9+\/=\s]+)-----END CERTIFICATE-----)|^(-----BEGIN PKCS7-----([A-Za-z0-9+\/=\s]+)-----END PKCS7-----)$
		PublicCertificate *string `json:"publicCertificate"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		ApplicationID string `json:"applicationId,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		ID string `json:"id,omitempty"`

		Metadata *AuditMetadata `json:"metadata,omitempty"`

		Name *string `json:"name"`

		Type string `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result PublicCertificateProfile

	result.applicationIdField = base.ApplicationID

	result.descriptionField = base.Description

	result.enabledField = base.Enabled

	result.idField = base.ID

	result.metadataField = base.Metadata

	result.nameField = base.Name

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.Login = data.Login
	result.PublicCertificate = data.PublicCertificate

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m PublicCertificateProfile) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// The login name
		// Required: true
		// Max Length: 256
		// Min Length: 1
		// Pattern: ^[^\!|\#|\*|\||\,|\;|\:]*$
		Login *string `json:"login"`

		// The public certificate in PKCS7, CRT, DER - PEM or Base64 encoded format
		// Required: true
		// Max Length: 524288
		// Pattern: ^(-----BEGIN CERTIFICATE-----([A-Za-z0-9+\/=\s]+)-----END CERTIFICATE-----)|^(-----BEGIN PKCS7-----([A-Za-z0-9+\/=\s]+)-----END PKCS7-----)$
		PublicCertificate *string `json:"publicCertificate"`
	}{

		Login: m.Login,

		PublicCertificate: m.PublicCertificate,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		ApplicationID string `json:"applicationId,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		ID string `json:"id,omitempty"`

		Metadata *AuditMetadata `json:"metadata,omitempty"`

		Name *string `json:"name"`

		Type string `json:"type"`
	}{

		ApplicationID: m.ApplicationID(),

		Description: m.Description(),

		Enabled: m.Enabled(),

		ID: m.ID(),

		Metadata: m.Metadata(),

		Name: m.Name(),

		Type: m.Type(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this public certificate profile
func (m *PublicCertificateProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApplicationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicCertificate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublicCertificateProfile) validateApplicationID(formats strfmt.Registry) error {

	if swag.IsZero(m.ApplicationID()) { // not required
		return nil
	}

	if err := validate.MinLength("applicationId", "body", m.ApplicationID(), 32); err != nil {
		return err
	}

	if err := validate.MaxLength("applicationId", "body", m.ApplicationID(), 32); err != nil {
		return err
	}

	return nil
}

func (m *PublicCertificateProfile) validateDescription(formats strfmt.Registry) error {

	if swag.IsZero(m.Description()) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description(), 350); err != nil {
		return err
	}

	if err := validate.Pattern("description", "body", m.Description(), `^[ -~\s]*$`); err != nil {
		return err
	}

	return nil
}

func (m *PublicCertificateProfile) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID()) { // not required
		return nil
	}

	if err := validate.MinLength("id", "body", m.ID(), 32); err != nil {
		return err
	}

	if err := validate.MaxLength("id", "body", m.ID(), 32); err != nil {
		return err
	}

	return nil
}

func (m *PublicCertificateProfile) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(m.Metadata()) { // not required
		return nil
	}

	if m.Metadata() != nil {
		if err := m.Metadata().Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *PublicCertificateProfile) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name()); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name(), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name(), 100); err != nil {
		return err
	}

	return nil
}

func (m *PublicCertificateProfile) validateLogin(formats strfmt.Registry) error {

	if err := validate.Required("login", "body", m.Login); err != nil {
		return err
	}

	if err := validate.MinLength("login", "body", *m.Login, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("login", "body", *m.Login, 256); err != nil {
		return err
	}

	if err := validate.Pattern("login", "body", *m.Login, `^[^\!|\#|\*|\||\,|\;|\:]*$`); err != nil {
		return err
	}

	return nil
}

func (m *PublicCertificateProfile) validatePublicCertificate(formats strfmt.Registry) error {

	if err := validate.Required("publicCertificate", "body", m.PublicCertificate); err != nil {
		return err
	}

	if err := validate.MaxLength("publicCertificate", "body", *m.PublicCertificate, 524288); err != nil {
		return err
	}

	if err := validate.Pattern("publicCertificate", "body", *m.PublicCertificate, `^(-----BEGIN CERTIFICATE-----([A-Za-z0-9+\/=\s]+)-----END CERTIFICATE-----)|^(-----BEGIN PKCS7-----([A-Za-z0-9+\/=\s]+)-----END PKCS7-----)$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this public certificate profile based on the context it is used
func (m *PublicCertificateProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublicCertificateProfile) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata() != nil {
		if err := m.Metadata().ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PublicCertificateProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicCertificateProfile) UnmarshalBinary(b []byte) error {
	var res PublicCertificateProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
