// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SFTPProfile s f t p profile
//
// swagger:model SFTPProfile
type SFTPProfile struct {
	applicationIdField string

	descriptionField string

	enabledField *bool

	idField string

	metadataField *AuditMetadata

	nameField *string

	SFTPProfileAllOf1

	// Type of Client Authentication
	// Enum: [PASSWORD PUBLIC_KEY PASSWORD_OR_PUBLIC_KEY]
	ClientAuthentication *string `json:"clientAuthentication,omitempty"`

	// Host of SFTP server
	// Required: true
	// Pattern: ^([a-zA-Z]\w+(\.?[\w-]+)+\.?)|((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$
	Host *string `json:"host"`

	// The port number on which to connect to SFTP server
	// Required: true
	// Maximum: 65535
	// Minimum: 1
	Port *int64 `json:"port"`
}

// ApplicationID gets the application Id of this subtype
func (m *SFTPProfile) ApplicationID() string {
	return m.applicationIdField
}

// SetApplicationID sets the application Id of this subtype
func (m *SFTPProfile) SetApplicationID(val string) {
	m.applicationIdField = val
}

// Description gets the description of this subtype
func (m *SFTPProfile) Description() string {
	return m.descriptionField
}

// SetDescription sets the description of this subtype
func (m *SFTPProfile) SetDescription(val string) {
	m.descriptionField = val
}

// Enabled gets the enabled of this subtype
func (m *SFTPProfile) Enabled() *bool {
	return m.enabledField
}

// SetEnabled sets the enabled of this subtype
func (m *SFTPProfile) SetEnabled(val *bool) {
	m.enabledField = val
}

// ID gets the id of this subtype
func (m *SFTPProfile) ID() string {
	return m.idField
}

// SetID sets the id of this subtype
func (m *SFTPProfile) SetID(val string) {
	m.idField = val
}

// Metadata gets the metadata of this subtype
func (m *SFTPProfile) Metadata() *AuditMetadata {
	return m.metadataField
}

// SetMetadata sets the metadata of this subtype
func (m *SFTPProfile) SetMetadata(val *AuditMetadata) {
	m.metadataField = val
}

// Name gets the name of this subtype
func (m *SFTPProfile) Name() *string {
	return m.nameField
}

// SetName sets the name of this subtype
func (m *SFTPProfile) SetName(val *string) {
	m.nameField = val
}

// Type gets the type of this subtype
func (m *SFTPProfile) Type() string {
	return "SFTPProfile"
}

// SetType sets the type of this subtype
func (m *SFTPProfile) SetType(val string) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *SFTPProfile) UnmarshalJSON(raw []byte) error {
	var data struct {
		SFTPProfileAllOf1

		// Type of Client Authentication
		// Enum: [PASSWORD PUBLIC_KEY PASSWORD_OR_PUBLIC_KEY]
		ClientAuthentication *string `json:"clientAuthentication,omitempty"`

		// Host of SFTP server
		// Required: true
		// Pattern: ^([a-zA-Z]\w+(\.?[\w-]+)+\.?)|((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$
		Host *string `json:"host"`

		// The port number on which to connect to SFTP server
		// Required: true
		// Maximum: 65535
		// Minimum: 1
		Port *int64 `json:"port"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		ApplicationID string `json:"applicationId,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		ID string `json:"id,omitempty"`

		Metadata *AuditMetadata `json:"metadata,omitempty"`

		Name *string `json:"name"`

		Type string `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result SFTPProfile

	result.applicationIdField = base.ApplicationID

	result.descriptionField = base.Description

	result.enabledField = base.Enabled

	result.idField = base.ID

	result.metadataField = base.Metadata

	result.nameField = base.Name

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}
	result.SFTPProfileAllOf1 = data.SFTPProfileAllOf1

	result.ClientAuthentication = data.ClientAuthentication
	result.Host = data.Host
	result.Port = data.Port

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m SFTPProfile) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {
		SFTPProfileAllOf1

		// Type of Client Authentication
		// Enum: [PASSWORD PUBLIC_KEY PASSWORD_OR_PUBLIC_KEY]
		ClientAuthentication *string `json:"clientAuthentication,omitempty"`

		// Host of SFTP server
		// Required: true
		// Pattern: ^([a-zA-Z]\w+(\.?[\w-]+)+\.?)|((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$
		Host *string `json:"host"`

		// The port number on which to connect to SFTP server
		// Required: true
		// Maximum: 65535
		// Minimum: 1
		Port *int64 `json:"port"`
	}{

		SFTPProfileAllOf1: m.SFTPProfileAllOf1,

		ClientAuthentication: m.ClientAuthentication,

		Host: m.Host,

		Port: m.Port,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		ApplicationID string `json:"applicationId,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		ID string `json:"id,omitempty"`

		Metadata *AuditMetadata `json:"metadata,omitempty"`

		Name *string `json:"name"`

		Type string `json:"type"`
	}{

		ApplicationID: m.ApplicationID(),

		Description: m.Description(),

		Enabled: m.Enabled(),

		ID: m.ID(),

		Metadata: m.Metadata(),

		Name: m.Name(),

		Type: m.Type(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this s f t p profile
func (m *SFTPProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApplicationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	// validation for a type composition with SFTPProfileAllOf1

	if err := m.validateClientAuthentication(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHost(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SFTPProfile) validateApplicationID(formats strfmt.Registry) error {

	if swag.IsZero(m.ApplicationID()) { // not required
		return nil
	}

	if err := validate.MinLength("applicationId", "body", m.ApplicationID(), 32); err != nil {
		return err
	}

	if err := validate.MaxLength("applicationId", "body", m.ApplicationID(), 32); err != nil {
		return err
	}

	return nil
}

func (m *SFTPProfile) validateDescription(formats strfmt.Registry) error {

	if swag.IsZero(m.Description()) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description(), 350); err != nil {
		return err
	}

	if err := validate.Pattern("description", "body", m.Description(), `^[ -~\s]*$`); err != nil {
		return err
	}

	return nil
}

func (m *SFTPProfile) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID()) { // not required
		return nil
	}

	if err := validate.MinLength("id", "body", m.ID(), 32); err != nil {
		return err
	}

	if err := validate.MaxLength("id", "body", m.ID(), 32); err != nil {
		return err
	}

	return nil
}

func (m *SFTPProfile) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(m.Metadata()) { // not required
		return nil
	}

	if m.Metadata() != nil {
		if err := m.Metadata().Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *SFTPProfile) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name()); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name(), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name(), 100); err != nil {
		return err
	}

	return nil
}

var sFTPProfileTypeClientAuthenticationPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["PASSWORD","PUBLIC_KEY","PASSWORD_OR_PUBLIC_KEY"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sFTPProfileTypeClientAuthenticationPropEnum = append(sFTPProfileTypeClientAuthenticationPropEnum, v)
	}
}

// property enum
func (m *SFTPProfile) validateClientAuthenticationEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, sFTPProfileTypeClientAuthenticationPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SFTPProfile) validateClientAuthentication(formats strfmt.Registry) error {

	if swag.IsZero(m.ClientAuthentication) { // not required
		return nil
	}

	// value enum
	if err := m.validateClientAuthenticationEnum("clientAuthentication", "body", *m.ClientAuthentication); err != nil {
		return err
	}

	return nil
}

func (m *SFTPProfile) validateHost(formats strfmt.Registry) error {

	if err := validate.Required("host", "body", m.Host); err != nil {
		return err
	}

	if err := validate.Pattern("host", "body", *m.Host, `^([a-zA-Z]\w+(\.?[\w-]+)+\.?)|((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$`); err != nil {
		return err
	}

	return nil
}

func (m *SFTPProfile) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	if err := validate.MinimumInt("port", "body", *m.Port, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("port", "body", *m.Port, 65535, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this s f t p profile based on the context it is used
func (m *SFTPProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	// validation for a type composition with SFTPProfileAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SFTPProfile) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata() != nil {
		if err := m.Metadata().ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SFTPProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SFTPProfile) UnmarshalBinary(b []byte) error {
	var res SFTPProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SFTPProfileAllOf1 Profile with host and port as required fields to be able to connect to SFTP server based on host and port
//
// swagger:model SFTPProfileAllOf1
type SFTPProfileAllOf1 interface{}
