// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SSHPublicKeyProfile SSH public key profile
//
// swagger:model SSHPublicKeyProfile
type SSHPublicKeyProfile struct {
	applicationIdField string

	descriptionField string

	enabledField *bool

	idField string

	metadataField *AuditMetadata

	nameField *string

	// The login name
	// Required: true
	// Max Length: 256
	// Min Length: 1
	// Pattern: ^[^\!|\#|\*|\||\,|\;|\:]*$
	Login *string `json:"login"`

	// The public ssh-key encoded in format specified by RFC-4254 or in PEM encoded format
	// Required: true
	// Max Length: 524288
	// Pattern: ^(-----BEGIN [^-]+-----([A-Za-z0-9+\/=\s]+)-----END [^-]+-----)|(ssh-[\w\sAAAA][0-9A-Za-z+/]+[=]{0,3} ([^@]+@[^@]+))*$
	PublicKey *string `json:"publicKey"`
}

// ApplicationID gets the application Id of this subtype
func (m *SSHPublicKeyProfile) ApplicationID() string {
	return m.applicationIdField
}

// SetApplicationID sets the application Id of this subtype
func (m *SSHPublicKeyProfile) SetApplicationID(val string) {
	m.applicationIdField = val
}

// Description gets the description of this subtype
func (m *SSHPublicKeyProfile) Description() string {
	return m.descriptionField
}

// SetDescription sets the description of this subtype
func (m *SSHPublicKeyProfile) SetDescription(val string) {
	m.descriptionField = val
}

// Enabled gets the enabled of this subtype
func (m *SSHPublicKeyProfile) Enabled() *bool {
	return m.enabledField
}

// SetEnabled sets the enabled of this subtype
func (m *SSHPublicKeyProfile) SetEnabled(val *bool) {
	m.enabledField = val
}

// ID gets the id of this subtype
func (m *SSHPublicKeyProfile) ID() string {
	return m.idField
}

// SetID sets the id of this subtype
func (m *SSHPublicKeyProfile) SetID(val string) {
	m.idField = val
}

// Metadata gets the metadata of this subtype
func (m *SSHPublicKeyProfile) Metadata() *AuditMetadata {
	return m.metadataField
}

// SetMetadata sets the metadata of this subtype
func (m *SSHPublicKeyProfile) SetMetadata(val *AuditMetadata) {
	m.metadataField = val
}

// Name gets the name of this subtype
func (m *SSHPublicKeyProfile) Name() *string {
	return m.nameField
}

// SetName sets the name of this subtype
func (m *SSHPublicKeyProfile) SetName(val *string) {
	m.nameField = val
}

// Type gets the type of this subtype
func (m *SSHPublicKeyProfile) Type() string {
	return "SSHPublicKeyProfile"
}

// SetType sets the type of this subtype
func (m *SSHPublicKeyProfile) SetType(val string) {
}

// UnmarshalJSON unmarshals this object with a polymorphic type from a JSON structure
func (m *SSHPublicKeyProfile) UnmarshalJSON(raw []byte) error {
	var data struct {

		// The login name
		// Required: true
		// Max Length: 256
		// Min Length: 1
		// Pattern: ^[^\!|\#|\*|\||\,|\;|\:]*$
		Login *string `json:"login"`

		// The public ssh-key encoded in format specified by RFC-4254 or in PEM encoded format
		// Required: true
		// Max Length: 524288
		// Pattern: ^(-----BEGIN [^-]+-----([A-Za-z0-9+\/=\s]+)-----END [^-]+-----)|(ssh-[\w\sAAAA][0-9A-Za-z+/]+[=]{0,3} ([^@]+@[^@]+))*$
		PublicKey *string `json:"publicKey"`
	}
	buf := bytes.NewBuffer(raw)
	dec := json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&data); err != nil {
		return err
	}

	var base struct {
		/* Just the base type fields. Used for unmashalling polymorphic types.*/

		ApplicationID string `json:"applicationId,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		ID string `json:"id,omitempty"`

		Metadata *AuditMetadata `json:"metadata,omitempty"`

		Name *string `json:"name"`

		Type string `json:"type"`
	}
	buf = bytes.NewBuffer(raw)
	dec = json.NewDecoder(buf)
	dec.UseNumber()

	if err := dec.Decode(&base); err != nil {
		return err
	}

	var result SSHPublicKeyProfile

	result.applicationIdField = base.ApplicationID

	result.descriptionField = base.Description

	result.enabledField = base.Enabled

	result.idField = base.ID

	result.metadataField = base.Metadata

	result.nameField = base.Name

	if base.Type != result.Type() {
		/* Not the type we're looking for. */
		return errors.New(422, "invalid type value: %q", base.Type)
	}

	result.Login = data.Login
	result.PublicKey = data.PublicKey

	*m = result

	return nil
}

// MarshalJSON marshals this object with a polymorphic type to a JSON structure
func (m SSHPublicKeyProfile) MarshalJSON() ([]byte, error) {
	var b1, b2, b3 []byte
	var err error
	b1, err = json.Marshal(struct {

		// The login name
		// Required: true
		// Max Length: 256
		// Min Length: 1
		// Pattern: ^[^\!|\#|\*|\||\,|\;|\:]*$
		Login *string `json:"login"`

		// The public ssh-key encoded in format specified by RFC-4254 or in PEM encoded format
		// Required: true
		// Max Length: 524288
		// Pattern: ^(-----BEGIN [^-]+-----([A-Za-z0-9+\/=\s]+)-----END [^-]+-----)|(ssh-[\w\sAAAA][0-9A-Za-z+/]+[=]{0,3} ([^@]+@[^@]+))*$
		PublicKey *string `json:"publicKey"`
	}{

		Login: m.Login,

		PublicKey: m.PublicKey,
	})
	if err != nil {
		return nil, err
	}
	b2, err = json.Marshal(struct {
		ApplicationID string `json:"applicationId,omitempty"`

		Description string `json:"description,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		ID string `json:"id,omitempty"`

		Metadata *AuditMetadata `json:"metadata,omitempty"`

		Name *string `json:"name"`

		Type string `json:"type"`
	}{

		ApplicationID: m.ApplicationID(),

		Description: m.Description(),

		Enabled: m.Enabled(),

		ID: m.ID(),

		Metadata: m.Metadata(),

		Name: m.Name(),

		Type: m.Type(),
	})
	if err != nil {
		return nil, err
	}

	return swag.ConcatJSON(b1, b2, b3), nil
}

// Validate validates this SSH public key profile
func (m *SSHPublicKeyProfile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApplicationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SSHPublicKeyProfile) validateApplicationID(formats strfmt.Registry) error {

	if swag.IsZero(m.ApplicationID()) { // not required
		return nil
	}

	if err := validate.MinLength("applicationId", "body", m.ApplicationID(), 32); err != nil {
		return err
	}

	if err := validate.MaxLength("applicationId", "body", m.ApplicationID(), 32); err != nil {
		return err
	}

	return nil
}

func (m *SSHPublicKeyProfile) validateDescription(formats strfmt.Registry) error {

	if swag.IsZero(m.Description()) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description(), 350); err != nil {
		return err
	}

	if err := validate.Pattern("description", "body", m.Description(), `^[ -~\s]*$`); err != nil {
		return err
	}

	return nil
}

func (m *SSHPublicKeyProfile) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID()) { // not required
		return nil
	}

	if err := validate.MinLength("id", "body", m.ID(), 32); err != nil {
		return err
	}

	if err := validate.MaxLength("id", "body", m.ID(), 32); err != nil {
		return err
	}

	return nil
}

func (m *SSHPublicKeyProfile) validateMetadata(formats strfmt.Registry) error {

	if swag.IsZero(m.Metadata()) { // not required
		return nil
	}

	if m.Metadata() != nil {
		if err := m.Metadata().Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

func (m *SSHPublicKeyProfile) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name()); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name(), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name(), 100); err != nil {
		return err
	}

	return nil
}

func (m *SSHPublicKeyProfile) validateLogin(formats strfmt.Registry) error {

	if err := validate.Required("login", "body", m.Login); err != nil {
		return err
	}

	if err := validate.MinLength("login", "body", *m.Login, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("login", "body", *m.Login, 256); err != nil {
		return err
	}

	if err := validate.Pattern("login", "body", *m.Login, `^[^\!|\#|\*|\||\,|\;|\:]*$`); err != nil {
		return err
	}

	return nil
}

func (m *SSHPublicKeyProfile) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.Required("publicKey", "body", m.PublicKey); err != nil {
		return err
	}

	if err := validate.MaxLength("publicKey", "body", *m.PublicKey, 524288); err != nil {
		return err
	}

	if err := validate.Pattern("publicKey", "body", *m.PublicKey, `^(-----BEGIN [^-]+-----([A-Za-z0-9+\/=\s]+)-----END [^-]+-----)|(ssh-[\w\sAAAA][0-9A-Za-z+/]+[=]{0,3} ([^@]+@[^@]+))*$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this SSH public key profile based on the context it is used
func (m *SSHPublicKeyProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SSHPublicKeyProfile) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if m.Metadata() != nil {
		if err := m.Metadata().ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SSHPublicKeyProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SSHPublicKeyProfile) UnmarshalBinary(b []byte) error {
	var res SSHPublicKeyProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
