// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserPreference user preference
//
// swagger:model UserPreference
type UserPreference struct {

	// The user preference field value
	// Max Length: 350
	// Pattern: ^[ -~\s]*$
	Value string `json:"value,omitempty"`
}

// Validate validates this user preference
func (m *UserPreference) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserPreference) validateValue(formats strfmt.Registry) error {
	if swag.IsZero(m.Value) { // not required
		return nil
	}

	if err := validate.MaxLength("value", "body", m.Value, 350); err != nil {
		return err
	}

	if err := validate.Pattern("value", "body", m.Value, `^[ -~\s]*$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user preference based on context it is used
func (m *UserPreference) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserPreference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserPreference) UnmarshalBinary(b []byte) error {
	var res UserPreference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
