// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ValidatedSwagger validated swagger
//
// swagger:model ValidatedSwagger
type ValidatedSwagger struct {

	// Content of the validated swagger
	Swagger string `json:"swagger,omitempty"`

	// Warnings generated after validating swagger
	Warnings []string `json:"warnings"`
}

// Validate validates this validated swagger
func (m *ValidatedSwagger) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this validated swagger based on context it is used
func (m *ValidatedSwagger) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidatedSwagger) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidatedSwagger) UnmarshalBinary(b []byte) error {
	var res ValidatedSwagger
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
