apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong-agents.fullname" . }}-discovery
  labels:
    {{- include "kong-agents.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.discovery.replicaCount }}
  selector:
    matchLabels:
      {{- include "kong-agents.selectorLabels" . | nindent 6 }}
      {{- with .Values.additionalLabels }}
      {{- range $key, $value := . }}
      {{ default "none" $key }}: {{ default "none" $value | quote }}
      {{- end }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kong-agents.selectorLabels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
        {{- range $key, $value := . }}
        {{ default "none" $key }}: {{ default "none" $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kong-agents.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.discovery.image.repository }}:{{ .Values.discovery.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.discovery.image.pullPolicy }}
          ports:
          - name: probe-port
            containerPort: {{ .Values.statusPort }}
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: probe-port
            {{- with .Values.livenessProbe }}
            {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
            {{- end }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /status
              port: probe-port
            {{- with .Values.readinessProbe }}
            {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
            {{- end }}
            {{- end }}
          env:
            - name: KONG_PROXY_HOST
              value: "{{ .Values.kong.proxy.host }}"
            - name: KONG_ACL_DISABLE
              value: "{{ .Values.kong.acl.disable }}"
            - name: KONG_PROXY_BASEPATH
              value: "{{ .Values.kong.proxy.basePath }}"
            - name: KONG_PROXY_PORTS_HTTP_VALUE
              value: "{{ .Values.kong.proxy.ports.http.value }}"
            - name: KONG_PROXY_PORTS_HTTPS_VALUE
              value: "{{ .Values.kong.proxy.ports.https.value }}"
            - name: KONG_PROXY_PORTS_HTTP_DISABLE
              value: "{{ .Values.kong.proxy.ports.http.disable }}"
            - name: KONG_PROXY_PORTS_HTTPS_DISABLE
              value: "{{ .Values.kong.proxy.ports.https.disable }}"
            - name: KONG_ADMIN_URL
              value: "{{ .Values.kong.admin.url }}"
            - name: KONG_ADMIN_SSL_NEXTPROTOS
              value: {{ include "kong-agents.admin.ssl.nextProtos.string" . }}
            - name: KONG_ADMIN_SSL_CIPHERSUITES
              value: {{ include "kong-agents.admin.ssl.cipherSuites.string" . }}
            - name: KONG_ADMIN_SSL_INSECURESKIPVERIFY
              value: "{{ .Values.kong.admin.ssl.insecureSkipVerify }}"
            - name: KONG_ADMIN_SSL_MAXVERSION
              value: "{{ .Values.kong.admin.ssl.maxVersion }}"
            - name: KONG_ADMIN_SSL_MINVERSION
              value: "{{ .Values.kong.admin.ssl.minVersion }}"
            {{- if (include "kong-agents.spec.urlPaths.string" .) }}
            - name: KONG_SPEC_URLPATHS
              value: {{ include "kong-agents.spec.urlPaths.string" . }}
            {{- end }}
            {{- if .Values.kong.spec.localPath }}
            - name: KONG_SPEC_LOCALPATH
              value: /specs
            {{- end }}
            {{- if .Values.kong.spec.filter }}
            - name: KONG_SPEC_FILTER
              value: "{{ .Values.kong.spec.filter }}"
            {{- end }}
            - name: "KONG_SPEC_CREATEUNSTRUCTUREDAPI"
              value: "{{ .Values.kong.spec.createUnstructuredAPI }}"
            {{- if .Values.kong.admin.auth.apikey.value }}
            - name: KONG_ADMIN_AUTH_APIKEY_VALUE
              valueFrom:
                secretKeyRef: 
                  name: kong-admin-auth-apikey
                  key: value
            - name: KONG_ADMIN_AUTH_APIKEY_HEADER
              valueFrom:
                secretKeyRef: 
                  name: kong-admin-auth-apikey
                  key: header
            {{- end }}
            {{- if .Values.kong.admin.auth.basicAuth.username }}
            - name: KONG_ADMIN_AUTH_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef: 
                  name: kong-admin-auth-basicauth
                  key: username
            - name: KONG_ADMIN_AUTH_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: kong-admin-auth-basicauth
                  key: password
            {{- end }}
          {{- with .Values.env }}
          {{- range $key, $value := . }}
          {{- if and (not (eq (toString $value) ""))
                     (not (eq (toString $key) ""))
                     (not (has (toString $key) (list "KONG_ACL_DISABLE"
                                                     "KONG_ADMIN_URL" 
                                                     "KONG_ADMIN_AUTH_APIKEY_HEADER" 
                                                     "KONG_ADMIN_AUTH_APIKEY_VALUE"
                                                     "KONG_ADMIN_AUTH_BASICAUTH_USERNAME"
                                                     "KONG_ADMIN_AUTH_BASICAUTH_PASSWORD"
                                                     "KONG_ADMIN_SSL_NEXTPROTOS"
                                                     "KONG_ADMIN_SSL_CIPHERSUITES"
                                                     "KONG_ADMIN_SSL_INSECURESKIPVERIFY"
                                                     "KONG_ADMIN_SSL_MAXVERSION"
                                                     "KONG_ADMIN_SSL_MINVERSION"
                                                     "KONG_PROXY_HOST" 
                                                     "KONG_PROXY_BASEPATH" 
                                                     "KONG_PROXY_PORTS_HTTP_VALUE" 
                                                     "KONG_PROXY_PORTS_HTTPS_VALUE" 
                                                     "KONG_PROXY_PORTS_HTTP_DISABLE" 
                                                     "KONG_PROXY_PORTS_HTTPS_DISABLE" 
                                                     "KONG_SPEC_LOCALPATH"
                                                     "KONG_SPEC_URLPATHS"
                                                     "KONG_SPEC_CREATEUNSTRUCTUREDAPI"
                                                     "KONG_LOGS_HTTP_SERVER_PATH"
                                                     "KONG_LOGS_HTTP_SERVER_PORT"
                                                     "STATUS_PORT")))
           }} 
            - name: {{ $key }}
              value: {{ $value | quote }} 
          {{- end }}
          {{- end }}
          {{- end }}
            - name: CENTRAL_AUTH_PRIVATEKEY
              value: "/keys/private_key.pem"
            - name: CENTRAL_AUTH_PUBLICKEY
              value: "/keys/public_key.pem"
            - name: STATUS_PORT
              value: "{{ .Values.statusPort }}"
          volumeMounts:
            - name: "kong-agent-keys"
              mountPath: "/keys"
          {{- if .Values.kong.spec.localPath }}
            - name: "kong-agent-specs"
              mountPath: "/specs"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: kong-agent-keys
        secret:
          secretName: {{ .Values.secrets.keys }}
          items:
          - key: private_key
            path: private_key.pem
          - key: public_key
            path: public_key.pem
      {{- if .Values.kong.spec.localPath }}
      {{- with .Values.kong.spec.localPath }}
      - name: kong-agent-specs
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
