{{- if .Values.kong.enable.traceability }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kong-agents.fullname" . }}-traceability
  labels:
    {{- include "kong-agents.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.traceability.replicaCount }}
  selector:
    matchLabels:
      {{- include "kong-agents.traceability.selectorLabels" . | nindent 6 }}
      {{- with .Values.additionalLabels }}
      {{- range $key, $value := . }}
      {{ default "none" $key }}: {{ default "none" $value | quote }}
      {{- end }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kong-agents.traceability.selectorLabels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
        {{- range $key, $value := . }}
        {{ default "none" $key }}: {{ default "none" $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kong-agents.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.traceability.image.repository }}:{{ .Values.traceability.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.traceability.image.pullPolicy }}
          ports:
          - name: probe-port
            containerPort: {{ .Values.statusPort }}
            protocol: TCP
          - name: logs
            containerPort: {{ .Values.kong.logs.http.port }}
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: probe-port
            {{- with .Values.livenessProbe }}
            {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
            {{- end }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /status
              port: probe-port
            {{- with .Values.readinessProbe }}
            {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
            {{- end }}
            {{- end }}
          env:
            - name: KONG_LOGS_HTTP_SERVER_PATH
              value: "{{ .Values.kong.logs.http.path }}"
            - name: KONG_LOGS_HTTP_SERVER_PORT
              value: "{{ .Values.kong.logs.http.port }}"
          {{- with .Values.env }}
          {{- range $key, $value := . }}
          {{- if and (not (eq (toString $value) ""))
                     (not (eq (toString $key) ""))
                     (not (has (toString $key) (list "KONG_ADMIN_URL" 
                                                     "KONG_ADMIN_AUTH_APIKEY_HEADER" 
                                                     "KONG_ADMIN_AUTH_APIKEY_VALUE" 
                                                     "KONG_PROXY_HOST" 
                                                     "KONG_PROXY_PORTS_HTTP" 
                                                     "KONG_PROXY_PORTS_HTTPS" 
                                                     "KONG_SPEC_LOCALPATH"
                                                     "KONG_SPEC_URLPATHS"
                                                     "KONG_LOGS_HTTP_SERVER_PATH"
                                                     "KONG_LOGS_HTTP_SERVER_PORT"
                                                     "STATUS_PORT")))
           }}
            - name: {{ $key }}
              value: {{ $value | quote }} 
          {{- end }}
          {{- end }}
          {{- end }}
            - name: CENTRAL_AUTH_PRIVATEKEY
              value: "/keys/private_key.pem"
            - name: CENTRAL_AUTH_PUBLICKEY
              value: "/keys/public_key.pem"
            - name: STATUS_PORT
              value: "{{ .Values.statusPort }}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: beat-storage
              mountPath: /data
            - name: "kong-agent-keys"
              mountPath: "/keys"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: beat-storage
        emptyDir: {}
      - name: kong-agent-keys
        secret:
          secretName: {{ .Values.secrets.keys }}
          items:
          - key: private_key
            path: private_key.pem
          - key: public_key
            path: public_key.pem
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}