{{- if .Values.kong.enable.traceability }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong-agents.fullname" . }}-traceability
  labels:
    {{- include "kong-agents.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.traceability.replicaCount }}
  selector:
    matchLabels:
      {{- include "kong-agents.selectorLabels" . | nindent 6 }}
      {{- with .Values.additionalLabels }}
      {{- range $key, $value := . }}
      {{ default "none" $key }}: {{ default "none" $value | quote }}
      {{- end }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kong-agents.selectorLabels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
        {{- range $key, $value := . }}
        {{ default "none" $key }}: {{ default "none" $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kong-agents.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.traceability.image.repository }}:{{ .Values.traceability.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.traceability.image.pullPolicy }}
          ports:
          - name: probe-port
            containerPort: {{ .Values.statusPort }}
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: probe-port
            {{- with .Values.livenessProbe }}
            {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
            {{- end }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /status
              port: probe-port
            {{- with .Values.readinessProbe }}
            {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
            {{- end }}
            {{- end }}
          env:
            - name: KONG_ADMIN_URL
              value: "{{ .Values.kong.admin.url }}"
            {{- if .Values.kong.admin.auth.apikey.value }}
            - name: KONG_ADMIN_AUTH_APIKEY_VALUE
              valueFrom:
                secretKeyRef: 
                  name: kong-admin-auth-apikey
                  key: value
            - name: KONG_ADMIN_AUTH_APIKEY_HEADER
              valueFrom:
                secretKeyRef: 
                  name: kong-admin-auth-apikey
                  key: header
            {{- end }}
          {{- with .Values.env }}
          {{- range $key, $value := . }}
          {{- if and (not (eq (toString $value) ""))
                     (not (eq (toString $key) ""))
                     (not (has (toString $key) (list "KONG_ADMIN_URL" 
                                                     "KONG_ADMIN_AUTH_APIKEY_HEADER" 
                                                     "KONG_ADMIN_AUTH_APIKEY_VALUE" 
                                                     "KONG_PROXY_HOST" 
                                                     "KONG_PROXY_PORTS_HTTP" 
                                                     "KONG_PROXY_PORTS_HTTPS" 
                                                     "KONG_SPEC_LOCALPATH"
                                                     "KONG_SPEC_URLPATHS")))
           }}
            - name: {{ $key }}
              value: {{ $value | quote }} 
          {{- end }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: "kong-agent-keys"
              mountPath: "/keys"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: kong-agent-keys
        secret:
          secretName: {{ .Values.secrets.keys }}
          items:
          - key: private_key
            path: private_key.pem
          - key: public_key
            path: public_key.pem
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}