name: Kong Discovery Agent Docker
on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    env:
      GOFLAGS: "-mod=mod"
      IMAGE_NAME: kong_discovery_agent
      ORG_NAME: Axway
      VERSION: ${{ github.ref_name }}
      COMMIT_ID: ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set output
        id: vars
        run: |
          echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "sdkversion=$(grep github.com/Axway/agent-sdk go.mod |  awk '{print $2}')" >> $GITHUB_OUTPUT
          echo "commit=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: ghcr.io/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/discovery/Dockerfile
          push: true
          build-args: |
            time=${{ steps.vars.outputs.date }}
            CGO_ENABLED=0
            version=${{ steps.vars.outputs.tag }}
            sdk_version=${{ steps.vars.outputs.sdkversion }}
            commit_id=${{ steps.vars.outputs.commit }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
