name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: '^1.16'
        - name: Checkout repository
          uses: actions/checkout@v2.3.4
        - name: Setup golangci-lint
          uses: golangci/golangci-lint-action@v2.5.2
          with:
            version: v1.40.1
        - name: Verify Codegen
          run: make verify-codegen
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: git.ecd.axway.org/apigov
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: |
        go build -v ./...
    - name: Test
      run: go test -v ./...
