name: Release agents with goreleaser
on:
  push:
    tags:
      - v*.*.*

jobs:
  discovery:
    runs-on: ubuntu-latest
    name: Release discovery
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Unshallow Fetch
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Export SDK Version # exports the SDK_VERSION to be used by the goreleaser
        run: echo "SDK_VERSION=$(make sdk-version)" >> $GITHUB_ENV
      - name: Discovery Release
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          args: release -f .goreleaser-da.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  traceability:
    runs-on: ubuntu-latest
    name: Release traceability
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Unshallow Fetch
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Export SDK Version # exports the SDK_VERSION to be used by the goreleaser
        run: echo "SDK_VERSION=$(make sdk-version)" >> $GITHUB_ENV
      - name: Traceability Release
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          args: release -f .goreleaser-ta.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notifyTeamsChannel:
    needs: [discovery, traceability]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Notify Teams channel
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          TAG: ${{ github.ref_name }}
        run: ./release.sh
